### ISSUE TITLE
zsort does not compile on Windows

### ISSUE THREAD

**Issue by MovieaT33** [mstdokumaci/zsort#14]
### Description

zsort 0.6.0 fails to compile on Windows with Zig 0.16.0 because it uses the old std.process.Args.Iterator.init API.

I know that the README already states:

> Requires Zig 0.15.2 or newer (including 0.16) on Linux or macOS. **On Windows, use WSL2**.

However, zsort can be made to work with a very small change. The current code in src/compat.zig uses:

```zig
std.process.Args.Iterator.init(args)
```

On Windows requires the allocator-aware version:

```zig
try std.process.Args.Iterator.initAllocator(args, allocator)
```

In my case, changing this required **only 24** characters to fix the compilation error. After this change, zsort successfully compiles. Would it be possible to add native Windows/Zig 0.16 support, or update the compatibility code accordingly?

**Environment**:

OS: Windows
zig: 0.16.0
zsort: 0.6.0

**Error**:

lib\std\process\Args.zig:39:36: error: In Windows, use initAllocator instead.
        if (native_os == .windows) @compileError("In Windows, use initAllocator instead.");
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

referenced by:
    collectArgs: zsort-0.6.0/src/compat.zig:196:44
    mainV16: zsort-0.6.0/src/compat.zig:183:41

This happens when zsort is used as a Zig build dependency and compiled for the native Windows host.

**Cause**:

src/compat.zig uses the old API:

std.process.Args.Iterator.init(...)

On Windows with Zig 0.16.0, initAllocator must be used instead.

**Possible fix**:

Changing the argument collection code to use:

-var it = std.process.Args.Iterator.init(args);
+var it = try std.process.Args.Iterator.initAllocator(args, allocator);

fixes the compilation error only on Windows.

**Comment by mstdokumaci** [comment]
@MovieaT33, that looks like a very small change indeed. I am still afraid to commit to keeping the code working on Windows without being able to test locally. Let me see how I can add this small diff to the compat.zig within a conditional block. But I will probably leave the promise in the README out; it can always break again later :(

**Comment by mstdokumaci** [comment]
fixed at v0.7.0
